app_main/urls.py
from django.contrib import admin
from django.urls import path, include

from app_docs import views_docs
from app_docs.views_Autocomplete import *

admin.site.site_header = "Creación/Almacenamiento de Documentos del ECUAPASS"
admin.site.site_title  = "Creación/Almacenamiento de Documentos del ECUAPASS"
admin.site.index_title = "Creación/Almacenamiento de Documentos del ECUAPASS Admin"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("usuarios/", include("app_usuarios.urls_user")),
    path("documentos/", include("app_docs.urls_docs")),
    path("cartaporte/", include("app_cartaporte.urls_cpi")),
    path("manifiesto/", include("app_manifiesto.urls_mci")),
    path("declaracion/", include("app_declaracion.urls_dti")),
    path("reportes/", include("appreportes.urls")),

    path('', views_docs.index, name='index'),
    #path('profile/', views_main.profile, name='profile'),
    #path('login/', views_main.login_view,  name='login'),
    #path('logout/', views_main.logout_view, name='logout'),
    #path('admin_panel/', views_main.admin_panel, name='admin_panel'), 	

	# Show autocomplete options
    path('opciones-cliente', ClienteOptionsView.as_view(), name='opciones-cliente'),
	path('opciones-lugar', CiudadPaisOptionsView.as_view(), name='opciones-lugar'),
	path('opciones-lugar-fecha', CiudadPaisFechaOptionsView.as_view(), name='opciones-lugar-fecha'),
	path('opciones-vehiculo', VehiculoOptionsView.as_view(), name='opciones-vehiculo'),
	path('opciones-conductor', ConductorOptionsView.as_view(), name='opciones-conductor'),
	path('opciones-cartaporte', CartaporteOptionsView.as_view(), name='opciones-cartaporte'),

	path('opciones-placa', PlacaOptionsView.as_view(), name='opciones-placa'),
	path('opciones-manifiesto', ManifiestoOptionsView.as_view(), name='opciones-manifiesto'),
]

app_usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import gettext_lazy as _
from django.urls import reverse

class UsuarioEcuapassManager (BaseUserManager):
	def create_user (self, username, email, password=None, **extra_fields):
		if not email:
			raise ValueError ('El correo es obligatorio')

		email = self.normalize_email (email)
		user  = self.model (username=username.strip (), email=email, **extra_fields)
		user.set_password (password)
		user.save (using=self._db)
		return user

	def create_superuser (self, username, email, password=None, **extra_fields):
		extra_fields.setdefault ('is_staff', True)
		extra_fields.setdefault ('is_superuser', True)
		extra_fields.setdefault ('perfil', 'director')

		if extra_fields.get ('is_staff') is not True:
			raise ValueError ('Superuser must have is_staff=True.')
		if extra_fields.get ('is_superuser') is not True:
			raise ValueError ('Superuser must have is_superuser=True.')

		return self.create_user (username, email, password, **extra_fields)

class UsuarioEcuapass (AbstractUser):
	PAIS_CHOICES = (('ECUADOR', 'ECUADOR'), ('COLOMBIA','COLOMBIA'),('PERU','PERU'),('TODOS','TODOS'),)
	USER_CHOICES = (('externo', 'Externo'), ('funcionario', 'Funcionario'), ('director', 'Director'),)
	class Meta:
		db_table = "usuarioecuapass"

	nombre	           = models.CharField (_ ('nombre'), max_length=100)
	pais               = models.CharField (max_length=20, choices=PAIS_CHOICES)
	perfil             = models.CharField (max_length=20, choices=USER_CHOICES)
	is_active	       = models.BooleanField (_ ('activo'), default=True)
	is_staff	       = models.BooleanField (_ ('staff'), default=False)
	es_director	       = models.BooleanField (default=False)
	es_funcionario	   = models.BooleanField (default=False)
	es_externo	       = models.BooleanField (default=True)
	date_joined        = models.DateTimeField (_ ('fecha de registro'), auto_now_add=True)
	nro_docs_creados   = models.IntegerField (default=0)
	nro_docs_asignados = models.IntegerField (default=0)


	username = models.CharField (_ ('nombre de usuario'), max_length=30, unique=True,
		help_text='Requerido. Letras y digitos, sin espacios ni carácteres, tildes o eñes.',
		validators=[], error_messages={ 'unique': "Este nombre de usuario ya está registrado..",},
	)
	email = models.EmailField (_ ('correo electrónico'), unique=True,
		help_text='Requerido.', 
		validators=[], error_messages={ 'unique': "Este correo ya está registrado..",},
	)

	def get_pais (self):
		return self.pais

	#-------------------------------------------------------------------
	# Methods for special column "Acciones" when listing users
	#-------------------------------------------------------------------
	def get_link_actualizar(self):
		return reverse('actualizar', args=[self.pk])

	def get_link_eliminar(self):
		return reverse('eliminar', args=[self.pk])

	#-------------------------------------------------------------------

	objects = UsuarioEcuapassManager ()

app_usuarios/forms.py
# from django import forms
# from .models import UsuarioEcuapass
# from django.contrib.auth.forms import UserCreationForm

# class RegistrationForm (UserCreationForm):
#	  email = forms.EmailField (required=True)
#	  class Meta:
#		  model = UsuarioEcuapass
#		  fields = ['username', 'email', 'perfil', 'password1', 'password2']

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import password_validation
from .models import UsuarioEcuapass

#----------------------------------------------------------
#----------------------------------------------------------
from django.contrib.auth.forms import AuthenticationForm

class CustomAuthenticationForm(AuthenticationForm):
	COUNTRY_CHOICES = [('', 'Seleccion el país'), ('ECUADOR','ECUADOR'),('COLOMBIA','COLOMBIA'),('PERU','PERU'),('TODOS','TODOS')]
	pais = forms.ChoiceField (choices=COUNTRY_CHOICES, required=True)

	username = forms.CharField(
		widget=forms.TextInput(attrs={'autofocus': True, 'autocomplete': 'off'})
	)
	password = forms.CharField(
		label=("Password"),
		strip=False,
		widget=forms.PasswordInput(attrs={'autocomplete': 'off'}),
	)

#----------------------------------------------------------
#----------------------------------------------------------
class RegistrationForm (UserCreationForm):
	email = forms.EmailField (required=False, widget=forms.EmailInput (attrs={'class': 'form-control'}))
	password1 = forms.CharField (
		label="Ingrese la Clave",
		widget=forms.PasswordInput (attrs={'class': 'form-control', 'id': 'password-input', 'autocomplete':'off'}),
		help_text=password_validation.password_validators_help_text_html (),
	)
	password2 = forms.CharField (
		label="Confirme la Clave",
		widget=forms.PasswordInput (attrs={'class': 'form-control', 'autocomplete':'off'}),
	)

	# Add an additional field for password strength
	password_strength = forms.CharField (
		widget=forms.HiddenInput (),
		required=False,
	)

	username = forms.CharField (
		label="Nombre Usuario",
		widget=forms.TextInput (attrs={'autocomplete':'off'}),
	)

	class Meta:
		model = UsuarioEcuapass
		fields =  ('username', 'email', 'nombre', 'pais', 'perfil', 'nro_docs_asignados')

	def __init__ (self, *args, **kwargs):
		super().__init__ (*args, **kwargs)
		self.fields ["username"].label = "Usuario"
		self.fields ["email"].label    = "Correo"
		self.fields ["nombre"].label   = "Nombre completo (Nombre + Apellido)"
		self.fields ["pais"].label	   = "Pais"
		self.fields ["perfil"].label   = "Tipo de usuario"

app_usuarios/views.py
from django.shortcuts import render, redirect
from .forms import RegistrationForm
from django.contrib import messages

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from django.contrib.auth.views import PasswordChangeView

from .models import UsuarioEcuapass
from .tables import UserTable
from .forms  import CustomAuthenticationForm

#----------------------------------------------------------
# Custom login view added "pais"
#----------------------------------------------------------
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
#from .forms import CountrySelectionForm

#----------------------------------------------------------
# Handling login
#----------------------------------------------------------
class CustomLoginView (LoginView):
	template_name = 'login.html'  # Update with your login template path
	authentication_form = CustomAuthenticationForm

	def get_context_data(self, **kwargs):
		context = super().get_context_data (**kwargs)
		return context

	def post (self, request, *args, **kwargs):
		print (f"\n\n\n+++ DEBUG: CustomLoginView POST '{request}'")
		auth_form    = self.authentication_form (data=request.POST)

		if auth_form.is_valid(): 
			# Process login and country selection
			request.session ['usuario'] = auth_form.cleaned_data ['username']
			request.session ['pais'] = auth_form.cleaned_data ['pais']
			request.session.save ()
			usuario = request.session ['usuario'] 
			pais    = request.session ['pais'] 
			print (f"+++ DEBUG: CustomLoginView self.request.session '{usuario}'")
			print (f"+++ DEBUG: CustomLoginView self.request.session '{pais}'")
			return self.form_valid (auth_form)
		else:
			return self.form_invalid (auth_form)

	def form_invalid(self, form):
		context = self.get_context_data (form=form)
		return self.render_to_response(context)
	
#----------------------------------------------------------
# Get username when called from html login template
#----------------------------------------------------------
from django.http import JsonResponse
from django.contrib.auth import get_user_model

User = get_user_model()

def get_country_for_username (request):
	username = request.POST.get ('username', None)
	data = {'pais': ''}
	print ("+++ DEBUG: get_country_for_username : username :", username)
	if username:
		try:
			user = User.objects.get (username=username)
			print ("+++ DEBUG: get_country_for_username : user.pais :", user.pais)
			data['pais'] = user.pais
		except User.DoesNotExist:
			data['pais'] = ''

	request.session ['pais']  = data ['pais']
	request.session.save ()
	return JsonResponse(data)

#----------------------------------------------------------
#----------------------------------------------------------
class UserCreate (LoginRequiredMixin, CreateView):
	model = UsuarioEcuapass
	fields = ['username','email', 'nombre', 'pais', 'password', 'perfil', 
	          'nro_docs_creados', 'nro_docs_asignados']
	template_name = 'user_create.html'
	success_url = reverse_lazy ('listar')

class UserDelete (LoginRequiredMixin, DeleteView):
	model = UsuarioEcuapass
	template_name = 'user_delete.html'
	success_url = reverse_lazy ('listar')

class UserUpdate (LoginRequiredMixin, UpdateView):
	model = UsuarioEcuapass
	fields = ['username','email', 'nombre', 'pais', 'perfil', 
	          'nro_docs_creados', 'nro_docs_asignados']
	template_name = 'user_update.html'
	success_url = reverse_lazy ('listar')

	def get_form(self, form_class=None):
		form = super().get_form (form_class)
		form.fields['username'].widget.attrs['readonly'] = True  # Set username field as readonly
		return form	

def user_list(request):
	print ("--- user_list ---")
	if (not request.user.is_staff):
		url =  reverse_lazy ("index")
		return redirect (url)

	users = UsuarioEcuapass.objects.all()
	table = UserTable (users)
	return render(request, 'user_list.html', {'table': table})	

def registration (request):
	if request.method == 'POST':
		# Create a form that has request.POST
		form = RegistrationForm(request.POST)
		if form.is_valid():
			user = form.save (commit=False)
			print (user)
			# Set the user's password securely
			username  = form.cleaned_data['username']		 
			password1 = form.cleaned_data['password1']
			password2 = form.cleaned_data['password2']

			# Set user type flag
			perfil              = form.cleaned_data['perfil']		 
			user.es_director    = perfil == "director"
			user.es_funcionario = perfil == "funcionario"
			user.es_externo     = perfil == "externo"

			user.is_staff       = user.es_director

			if password1 == password2:
				user.set_password (password1)
				user.save()
				
				messages.success(request, f'Su cuenta ha sido creada {username} ! Proceda a ingresar')
				return redirect('listar')  # Redirect to the login page
			else:
				# Handle password mismatch error here
				form.add_error('password2', 'Claves ingresadas no coinciden')

	else:
		form = RegistrationForm()
	return render(request, 'registration.html', {'form': form})

#----------------------------------------------------------
# Password change view
#----------------------------------------------------------
class CustomPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
	template_name = 'password_change_form.html'
	success_url   = reverse_lazy('login')
	success_message = "Cambio exitoso. Por favor ingrese con su nueva clave"

app_usuarios/templates/back/base_usuarios.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
	{% block title %}<title>Ecuapass Usuarios</title>{% endblock %}
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="{% static 'app_docs/css/bootstrap.min.css' %}" rel="stylesheet">
	<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
	<!--link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"-->
		
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

	<!-- Add additional CSS in static file -->
	{% load static %}
	<link rel="stylesheet"	href="{% static 'appdocs/css/styles.css' %}">

	<!-- Remove cache -->
	<meta http-equiv="Cache-Control" content="no-store" />
    	<meta http-equiv="Pragma" content="no-cache" />
    	<meta http-equiv="Expires" content="0" />
</head>

<body>
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-2">
				<ul class="sidebar-title">
					<b>EcuapassDocs01</b>
				</ul>

				<ul class="sidebar-nav">
					{% if user.is_authenticated %}
						<li>Usuario: {{ user.get_username }}</li>
						<li>
							<form method="post" action="{% url 'logout' %}">
							  {% csrf_token %}
							  <button type="submit">Cerrar sesión</button>
							</form>
						</li>
					{% else %}
						<li><a href="{% url 'index' %}">Inicio</a></li>					   
						<li><a href="{% url 'login'%}">Iniciar sesión</a></li>
					{% endif %}
				</ul>


				{% if user.is_staff %}
					<ul class="sidebar-nav">
						<b>Usuarios:</b>
						<li><a href="{% url 'listar' %}" >Listar</a>
						<li><a href="{% url 'registration' %}" >Crear</a>
						<li><a href="{% url 'login' %}" >Ingresar</a>
					</ul>

					<ul class="sidebar-nav">
						<b>Creación entidades:</b>
						<li><a href="{% url 'cliente-create' %}">Nueva Cliente</a></li>
						<li><a href="{% url 'vehiculo-create' %}">Nuevo Vehículo</a></li>
						<li><a href="{% url 'conductor-create' %}">Nuevo Conductor</a></li>
					</ul>

					<ul class="sidebar-nav">
						<li><a href="{% url 'info_view' %}">Información de Contacto</a></li>				  
					</ul>
					{% endif %}  

			</div>
			<div class="col-sm-10 ">
				{% block content %}{% endblock %}
			</div>
		</div>
	</div>
</body>

</html>

app_usuarios/templates/back/login.html
{% extends "base_main.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<!--script src="https://code.jquery.com/jquery-3.6.0.min.js"></script-->
<script src="{% static 'app_docs/js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'app_docs/js/csrf_utils.js' %}"></script>

<div class="container"> 
    <h2>Ingreso</h2>
	<form id="login" method="POST", action="">
        {% csrf_token %}
        <!-- Display the authentication form -->
        {{ form|crispy }}
        <button id="submit" class="btn btn-primary" type="submit">Ingreso</button>
    </form>
</div>
<script>
	// Script showing the user's "pais" 
	$('#id_username').on('blur', function() {
		var username = $(this).val();
		console.log (">>> username", username);
		csrftoken = getCookie ('csrftoken');

		$.ajax({
			type     : "POST",
		    url      : "{% url 'get_country_for_username' %}",  // URL for the AJAX view
			data     : {'username': username, 'csrfmiddlewaretoken': csrftoken},
		    dataType : 'json',
		    success  : function(data) {
				$('#id_pais').html('');
				if (data.pais) 
					$('#id_pais').append('<option value="' + data.pais + '">' + data.pais + '</option>');
				else 
					$('#id_pais').append('<option value="">No country found</option>');
				}
		});
});
		
</script>

{% endblock %}
    

app_usuarios/templates/back/logout-post.html
<form method="post" action="{% url 'logout' %}">
    {% csrf_token %}
    <button type="submit">Logout</button>
</form>

app_usuarios/templates/back/logout.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 mx-auto text-center">
            <div class="card">
                <div class="card-header">
                    <h2>You have been logged out</h2>
                </div>
                <div class="card-body">
                    <p class="card-text">Thank you for using our service. If you'd like to continue, please log in again.</p>
                </div>
                <div class="card-footer">
                    <small class="text-muted">
                        <a href="{% url 'login' %}" class="btn btn-primary">Log In Again</a>
                    </small>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

app_usuarios/templates/back/password_change_form.html
{% extends "base_main.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h2>Cambiar su contraseña</h2>
<form method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_old_password">Contraseña actual:</label>
        {{ form.old_password }}
    </div>
    <div class="form-group">
        <label for="id_new_password1">Nueva Contraseña:</label>
        {{ form.new_password1 }}
    </div>
    <div class="form-group">
        <label for="id_new_password2">Confirmar Contraseña:</label>
        {{ form.new_password2 }}
    </div>
    <button type="submit" class="btn btn-primary">Cambiar Contraseña</button>
</form>

{% if form.errors %}
    <div class="alert alert-danger">
        <ul>
            {% for field in form %}
                {% for error in field.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            {% endfor %}
        </ul>
    </div>
{% endif %}

{% endblock %}

app_usuarios/templates/back/registration-org.html
{% extends 'app_usuarios/base_usuarios.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h2>Registro</h2>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <div>
            <strong>Fortaleza de la Clave:</strong>
            <div id="password-strength">Ingrese una clave.</div>
        </div>
        <button type="submit" class="btn btn-primary" style="margin-top: 8px;">Registro</button>
    </form>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/zxcvbn/4.4.2/zxcvbn.js"></script>
<script>
document.addEventListener('DOMContentLoaded', function () {
    const passwordInput = document.getElementById('password-input');
    const passwordStrengthField = document.getElementById('password-strength');

    passwordInput.addEventListener('input', function () {
        const password = passwordInput.value;
        const result = zxcvbn(password);

        // Update password strength feedback
        passwordStrengthField.innerHTML = ''; // Clear previous feedback

        if (result.score === 0) {
            passwordStrengthField.innerHTML = '<span style="color: red;">Very Weak</span>';
        } else if (result.score === 1) {
            passwordStrengthField.innerHTML = '<span style="color: orange;">Weak</span>';
        } else if (result.score === 2) {
            passwordStrengthField.innerHTML = '<span style="color: yellow;">Medium</span>';
        } else if (result.score === 3) {
            passwordStrengthField.innerHTML = '<span style="color: green;">Strong</span>';
        } else if (result.score === 4) {
            passwordStrengthField.innerHTML = '<span style="color: darkgreen;">Very Strong</span>';
        }
    });
});
</script>
{% endblock %}

app_usuarios/templates/back/registration.html
{% extends 'base_usuarios.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <h2>Registro de un Nuevo Usuario</h2>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <div>
            <strong>Fortaleza de la Clave:</strong>
            <div id="password-strength">Ingrese una clave.</div>
        </div>
		<!-- Submit button -->
        <button type="submit" class="btn btn-primary" style="margin-top: 8px;">Registrar</button>
		<!-- Cancel button -->
		<a href="{% url 'listar' %}" class="btn btn-secondary" style="margin-top: 8px;">Cancelar</a>
    </form>
</div>

{% endblock %}

app_usuarios/templates/back/user_delete.html
{% extends 'base_usuarios.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container"> 
	<h2>Eliminación de un Usuario</h2>
		<form method="post">
			{% csrf_token %}
			{{ form|crispy }}
			<p>Está seguro de querer eliminar al usuario <b>'{{ object }}'</b> ?</p>

			<button type="submit" class="btn btn-primary">Eliminar</button>
			<a href="{% url 'listar' %}" class="btn btn-secondary">Cancelar</a>

		</form>
</div>
{% endblock content %}

app_usuarios/templates/back/user_list.html
{% extends 'base_usuarios.html' %}

{% load render_table from django_tables2 %}

{% block content %}

<div class="container">
    <h2>Lista de Usuarios</h2>
	<!DOCTYPE html>
	<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>User List</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
	</head>
	<body>
		{% render_table table %}
	</body>
	</html>
</div>

{% endblock %}

app_usuarios/templates/back/user_update.html
{% extends 'base_usuarios.html' %}
{% load crispy_forms_tags %}

{% block content %}
	<div class="container">
		<h2>Actualizacion de Datos</h2>
		<form method="post">
			{% csrf_token %}
			{{ form|crispy }}

			<!-- Submit button -->
			<button type="submit" class="btn btn-primary">Actualizar</button>
			<!-- Cancel button -->
			<a href="{% url 'listar' %}" class="btn btn-secondary">Cancelar</a>

		</form>
	</div>
{% endblock %}